[package]
name = "markov-chains"
version = "1.4.4"
description = "Haha funny text generator with markov chains"
authors = ["Nikita Podvirnyi <krypt0nn@vk.com>"]
homepage = "https://github.com/krypt0nn/markov-chains"
repository = "https://github.com/krypt0nn/markov-chains"
license = "MIT"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
strip = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

mimalloc = "0.1"
smol = "2.0"
futures = { version = "0.3", features = ["alloc"] }
clap = { version = "4.5", features = ["derive"] }

fastrand = "2.2"
anyhow = "1.0"
tinyvec = { version = "1.8", features = ["alloc"] }
strumbra = "0.5.2"
crc32fast = "1.4.2"
intmap = "2.0.0"

lz4_flex = "0.11.3"
brotli = "7.0.0"
zstd = "0.13.2"
